"""Generate the API reference pages under docs/api/ from the package itself.

One MDX page per public module group, one section per name in ``__all__``:
the signature as the interpreter sees it, then the docstring. The docs site
(Mintlify, reading docs/) renders them; ``--check`` fails when the committed
pages differ from what the installed package would produce, so a PR that
changes a public signature or docstring must regenerate them. Fix:

    uv run python scripts/gen_api_docs.py

then commit docs/api/ and docs/docs.json.
"""

from __future__ import annotations

import argparse
import importlib
import inspect
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
API = DOCS / "api"
DOCS_JSON = DOCS / "docs.json"
ROOTS = ("whileai", "whileai.simulations")
GENERATED = (
    "{/* Generated by scripts/gen_api_docs.py from the package. Do not edit; fix the docstring. */}"
)

# Groups that lead the sidebar; everything else follows alphabetically.
FIRST = ["whileai", "simulations"]

GROUP_BLURB = {
    "whileai": "The platform client: login, trace ingest, account.",
    "simulations": "The top-level calls: simulate, grade, optimize, export, train.",
    "constants": "Module-level constants and their defaults.",
}


def _module_group(root: str, name: str, obj: object) -> str:
    if root == "whileai":
        return "whileai"
    mod = getattr(obj, "__module__", None)
    if inspect.ismodule(obj):
        mod = obj.__name__
    if not isinstance(mod, str) or not mod.startswith("whileai.simulations"):
        return "constants"
    rest = mod[len("whileai.simulations") :].lstrip(".")
    return rest.split(".")[0] if rest else "simulations"


def _clean_signature(obj: object, name: str) -> str | None:
    if not callable(obj):
        return None
    try:
        sig = inspect.signature(obj)
    except (TypeError, ValueError):
        return None
    params = [str(p) for p in sig.parameters.values()]
    ret = ""
    if sig.return_annotation is not inspect.Signature.empty:
        ann = sig.return_annotation
        ret = " -> " + (ann if isinstance(ann, str) else inspect.formatannotation(ann))
    one = f"{name}({', '.join(params)}){ret}"
    if len(one) > 84 and params:
        body = "".join(f"    {p},\n" for p in params)
        one = f"{name}(\n{body}){ret}"
    one = re.sub(r" at 0x[0-9a-fA-F]+", "", one)
    one = re.sub(r"(: |-> )'([^']*)'", r"\1\2", one)
    return one


def _escape_prose(line: str) -> str:
    """Escape what MDX would read as JSX or an expression, outside inline code."""
    parts = re.split(r"(`[^`]*`)", line)
    for i in range(0, len(parts), 2):
        s = parts[i]
        s = s.replace("{", "\\{").replace("}", "\\}")
        s = re.sub(r"<(?=[A-Za-z/!])", "&lt;", s)
        parts[i] = s
    return "".join(parts)


def _docstring(obj: object) -> str:
    doc = inspect.getdoc(obj) or ""
    doc = re.sub(r"``([^`]+)``", r"`\1`", doc)
    out: list[str] = []
    in_fence = False
    in_doctest = False
    for line in doc.split("\n"):
        if line.startswith("```"):
            in_fence = not in_fence
            out.append(line)
            continue
        if in_fence:
            out.append(line)
            continue
        is_doctest = line.lstrip().startswith(">>>") or (in_doctest and line.strip())
        if is_doctest and not in_doctest:
            out.append("```python")
            in_doctest = True
        elif not is_doctest and in_doctest:
            out.append("```")
            in_doctest = False
        out.append(line if in_doctest else _escape_prose(line))
    if in_doctest:
        out.append("```")
    return "\n".join(out).strip()


def _section(name: str, obj: object, level: str) -> str:
    parts = [f"{level} `{name}`", ""]
    if inspect.ismodule(obj):
        parts.append(f"Module `{obj.__name__}`.")
    else:
        sig = _clean_signature(obj, name.split(".")[-1])
        if sig is not None:
            parts += ["```python", sig, "```"]
        elif not (inspect.isclass(obj) or callable(obj)):
            parts += ["```python", f"{name.split('.')[-1]} = {_short_repr(obj)}", "```"]
    doc = _docstring(obj)
    if doc and not _is_builtin_doc(obj, doc):
        parts += ["", doc]
    if inspect.isclass(obj):
        for mname, member in sorted(vars(obj).items()):
            if mname.startswith("_") or not inspect.isfunction(member):
                continue
            if not inspect.getdoc(member):
                continue
            parts += ["", _section(f"{name}.{mname}", member, level + "#")]
    return "\n".join(parts)


def _short_repr(obj: object) -> str:
    r = repr(obj)
    r = re.sub(r" at 0x[0-9a-fA-F]+", "", r)
    return r if len(r) <= 200 else r[:197] + "..."


def _is_builtin_doc(obj: object, doc: str) -> bool:
    """Constants inherit the docstring of their type; that is not documentation."""
    if inspect.isclass(obj) or inspect.isroutine(obj) or inspect.ismodule(obj):
        return False
    return inspect.getdoc(type(obj)) == inspect.getdoc(obj)


def _render_page(root: str, group: str, names: list[tuple[str, object]]) -> str:
    modname = root if group in ("whileai", "simulations") else f"{root}.{group}"
    title = modname
    blurb = GROUP_BLURB.get(group, "")
    intro = ""
    if group not in ("constants",):
        try:
            mod = importlib.import_module(modname)
            intro = _docstring(mod) if group not in ("whileai", "simulations") else ""
        except ImportError:
            intro = ""
    desc = blurb or (intro.split("\n")[0][:150] if intro else f"Public names in {modname}.")
    desc = desc.replace('"', "'")
    head = [
        "---",
        f'title: "{title}"',
        f'description: "{desc}"',
        "---",
        "",
        GENERATED,
        "",
    ]
    body: list[str] = []
    if intro:
        body += [intro, ""]
    body.append(
        f"{len(names)} public names. Import with `import {root} as wai`."
        if root.endswith("simulations")
        else f"{len(names)} public names. Import with `import {root}`."
    )
    for name, obj in names:
        body += ["", _section(name, obj, "###")]
    return "\n".join(head + body) + "\n"


def build() -> dict[str, str]:
    pages: dict[str, str] = {}
    groups: dict[tuple[str, str], list[tuple[str, object]]] = defaultdict(list)
    for root in ROOTS:
        mod = importlib.import_module(root)
        for name in sorted(getattr(mod, "__all__", ())):
            if name == "__version__":
                continue
            obj = getattr(mod, name)
            groups[(root, _module_group(root, name, obj))].append((name, obj))
    for (root, group), names in groups.items():
        pages[f"api/{group}.mdx"] = _render_page(root, group, names)
    by_group = {g: names for (_, g), names in groups.items()}
    order = [g for g in FIRST if g in by_group] + sorted(g for g in by_group if g not in FIRST)
    rows = "\n".join(
        f"| [{g}](/api/{g}) | {len(by_group[g])} | {GROUP_BLURB.get(g, '')} |" for g in order
    )
    pages["api/index.mdx"] = (
        "---\n"
        'title: "API reference"\n'
        'description: "Every public name in whileai and whileai.simulations, with its signature and docstring, generated from the package."\n'
        "---\n\n"
        f"{GENERATED}\n\n"
        "These pages are generated from the installed package on each change, so a\n"
        "signature here is the signature the interpreter sees. The prose that says\n"
        "when to use which call is in the [reference](/reference).\n\n"
        "| Page | Names | What it holds |\n|---|---|---|\n"
        f"{rows}\n"
    )
    return pages


def nav_pages(pages: dict[str, str]) -> list[str]:
    groups = [p[len("api/") : -len(".mdx")] for p in pages if p != "api/index.mdx"]
    order = [g for g in FIRST if g in groups] + sorted(g for g in groups if g not in FIRST)
    return ["api/index"] + [f"api/{g}" for g in order]


def updated_docs_json(pages: dict[str, str]) -> str:
    cfg = json.loads(DOCS_JSON.read_text(encoding="utf-8"))
    for group in cfg["navigation"]["groups"]:
        if group["group"] == "API":
            group["pages"] = nav_pages(pages)
            break
    else:
        raise SystemExit('docs/docs.json has no navigation group named "API"')
    return json.dumps(cfg, indent=2) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if docs/api/ is stale")
    args = ap.parse_args(argv)
    pages = build()
    pages["docs.json"] = updated_docs_json(pages)
    stale: list[str] = []
    for rel, text in pages.items():
        path = DOCS / rel
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            stale.append(rel)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8", newline="\n")
    extra = [p.name for p in API.glob("*.mdx") if f"api/{p.name}" not in pages]
    if args.check:
        if stale or extra:
            print(
                "docs/api/ is stale for:", ", ".join(stale + [f"api/{e} (remove)" for e in extra])
            )
            print(
                "Fix: uv run python scripts/gen_api_docs.py  # then commit docs/api/ and docs/docs.json"
            )
            return 1
        print(f"docs/api/ is current ({len(pages) - 1} pages)")
        return 0
    for e in extra:
        (API / e).unlink()
    print(f"wrote {len(stale)} file(s); {len(pages) - 1} pages under docs/api/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
